### ISSUE TITLE
Delay between frames

### ISSUE THREAD

**Issue by kevinetta** [drewsum/Electronic_Display#111]
Store the amount of time in seconds that each frame should be displayed (before screen-switching to the next frame in flash) in the header struct of each flash chip. This value can be parsed when the flash chip is accessed to be used by a timer. On the app side, when adding a frame to a project, a value must be entered for display time, with a default of 10 seconds.

A theoretical workflow on the embedded side would check the flash chip for if there is a frame stored in it ( a byte should be used in the header of each flash chip to tell this) and if there is that header should also contain the time delay of how long to display the image, all followed by the image bytes.

**Comment by drewsum** [comment]
Got this figured out, closing
