### ISSUE TITLE
Block screen rotation on the upload project screen

### ISSUE THREAD

**Issue by drewsum** [drewsum/Electronic_Display#148]
I noticed a bug in the android app. When you rotate the screen (I do this by accident sometimes) the progress bar disappears. Data transfer continues, but I'm pretty sure image data is corrupted. To keep this from happening, we should disable screen rotation.

**Comment by kevinetta** [comment]
I'll work on this Monday

**Comment by drewsum** [comment]
Maybe we should also add text to the upload screen while uploading that says "please do not leave the app", I ran into trouble trying to send text messages while connected to the ESP

**Comment by kevinetta** [comment]
Easy fix but also should this be expected?
